# Generated by Django 3.2.6 on 2022-06-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220626_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicationslinks',
            name='pintrist',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
